{
 "title": "API / Endpoint",
 "tags": [ "nginx" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": "label_values(nginx_http_request_duration_seconds_count, host)"
   },
   {
    "name": "endpoint",
    "label": "endpoint",
    "query": "label_values(nginx_http_request_duration_seconds_count{host=~\"$host\"}, endpoint)"
   }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ERROR Rate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "job:nginx_http_request_duration_seconds_sum:err_rate_by_host_endpoint_fullurl{host=~\"$host\", endpoint=~\"$endpoint\"}",
     "legendFormat": "{{fullurl}}"
    }
   ]
  },
  {
   "title": "2XX QPS By Instance",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:nginx_http_request_duration_seconds:qps_by_instance_host_endpoint_2XX{host=~\"$host\", endpoint=~\"$endpoint\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(job:nginx_http_request_duration_seconds:qps_by_instance_host_endpoint_2XX{host=~\"$host\", endpoint=~\"$endpoint\"})",
     "legendFormat": "2XX"
    }
   ]
  },
  { "title": "URL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "TOP 10 QPS",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "topk(10, sum by(fullurl) (job:nginx_http_request_duration_seconds:qps_by_instance_host_endpoint_fullurl_2XX{host=~\"$host\", endpoint=~\"$endpoint\"}))"
    }
   ]
  },
  {
   "title": "TOP 10 4XX over 10min",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "topk(10, sum by (fullurl)(increase(nginx_http_request_duration_seconds_count{host=~\"$host\", status=~\"40[^3]{1}|4[^0]{1}.\", endpoint=~\"$endpoint\"}[10m]))>0)"
    }
   ]
  },
  {
   "title": "TOP 10 5XX over 10min",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "topk(10, sum by (fullurl)(increase(nginx_http_request_duration_seconds_count{host=~\"$host\", status=~\"5..\", endpoint=~\"$endpoint\"}[10m]))>0)"
    }
   ]
  }
 ]
}