{
 "title": "API / Endpoint / URL",
 "tags": [ "nginx" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": "label_values(nginx_http_request_duration_seconds_count, host)"
   },
   {
    "name": "endpoint",
    "label": "endpoint",
    "query": "label_values(nginx_http_request_duration_seconds_count{host=~\"$host\"}, endpoint)"
   },
   {
    "name": "fullurl",
    "label": "fullurl",
    "query": "label_values(nginx_http_request_duration_seconds_count{host=~\"$host\",endpoint=~\"$endpoint\"}, fullurl)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "ERROR Rate",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "job:nginx_http_request_duration_seconds_sum:err_rate_by_host_endpoint_fullurl{host=~\"$host\", endpoint=~\"$endpoint\"}",
       "legendFormat": "{{fullurl}}"
      }
     ]
    },
    {
     "title": "QPS",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(job:nginx_http_request_duration_seconds:qps_by_instance_host_endpoint_fullurl_2XX{host=~\"$host\", endpoint=~\"$endpoint\"}) by (fullurl)",
       "legendFormat": "{{fullurl}}"
      }
     ]
    }
   ]
  },
  { "title": "$fullurl", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }, "repeat": "fullurl" },
  {
   "title": "ERROR Count（5 min）",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_http_request_duration_seconds_count{endpoint=~\"[[endpoint]]\", fullurl=~\"[[fullurl]]\", status=~\"3..\"}[5m]))",
     "legendFormat": "3XX"
    },
    {
     "expr": "sum(increase(nginx_http_request_duration_seconds_count{endpoint=~\"[[endpoint]]\", fullurl=~\"[[fullurl]]\", status=~\"40[^3]{1}|4[^0]{1}.\"}[5m]))",
     "legendFormat": "4XX(with out 401 & 403)"
    },
    {
     "expr": "sum(increase(nginx_http_request_duration_seconds_count{endpoint=~\"[[endpoint]]\", fullurl=~\"[[fullurl]]\", status=~\"5..\"}[5m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(job:nginx_http_request_duration_seconds:p999_by_host_instance_fullurl_2XX{host=~\"[[host]]\", fullurl=~\"[[fullurl]]\"} > 0)",
     "legendFormat": "p999"
    },
    {
     "expr": "avg(job:nginx_http_request_duration_seconds:p99_by_host_instance_fullurl_2XX{host=~\"[[host]]\", fullurl=~\"[[fullurl]]\"} > 0)",
     "legendFormat": "p99"
    },
    {
     "expr": "avg(job:nginx_http_request_duration_seconds:p90_by_host_instance_fullurl_2XX{host=~\"[[host]]\", fullurl=~\"[[fullurl]]\"} > 0)",
     "legendFormat": "p90"
    },
    {
     "expr": "avg(job:nginx_http_request_duration_seconds:avg_by_host_instance_fullurl_2XX{host=~\"[[host]]\", fullurl=~\"[[fullurl]]\"} > 0)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "2XX QPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(job:nginx_http_request_duration_seconds:qps_by_instance_host_endpoint_fullurl_2XX{host=~\"$host\", endpoint=~\"$endpoint\", fullurl=~\"$fullurl\"})",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "2XX P90",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "job:nginx_http_request_duration_seconds:p90_by_host_instance_fullurl_2XX{host=~\"$host\", fullurl=~\"[[fullurl]]\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "2XX P99",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "job:nginx_http_request_duration_seconds:p99_by_host_instance_fullurl_2XX{host=~\"$host\", fullurl=~\"[[fullurl]]\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "2XX P999",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "job:nginx_http_request_duration_seconds:p999_by_host_instance_fullurl_2XX{host=~\"$host\", fullurl=~\"[[fullurl]]\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "2XX QPS By Instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:nginx_http_request_duration_seconds:qps_by_instance_host_endpoint_fullurl_2XX{host=~\"$host\", endpoint=~\"$endpoint\", fullurl=~\"$fullurl\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "P90 - 同比环比",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(job:nginx_http_request_duration_seconds:p90_by_host_instance_fullurl_2XX{host=~\"[[host]]\", fullurl=~\"[[fullurl]]\"} > 0)",
     "legendFormat": "当日-p90"
    },
    {
     "expr": "avg(job:nginx_http_request_duration_seconds:p90_by_host_instance_fullurl_2XX{host=~\"[[host]]\", fullurl=~\"[[fullurl]]\"} offset 24h > 0)",
     "legendFormat": "昨日-p90"
    },
    {
     "expr": "avg(job:nginx_http_request_duration_seconds:p90_by_host_instance_fullurl_2XX{host=~\"[[host]]\", fullurl=~\"[[fullurl]]\"} offset 7d > 0)",
     "legendFormat": "上周-p90"
    }
   ]
  },
  {
   "title": "P99 - 同比环比",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(job:nginx_http_request_duration_seconds:p99_by_host_instance_fullurl_2XX{host=~\"[[host]]\", fullurl=~\"[[fullurl]]\"} > 0)",
     "legendFormat": "当日-p99"
    },
    {
     "expr": "avg(job:nginx_http_request_duration_seconds:p99_by_host_instance_fullurl_2XX{host=~\"[[host]]\", fullurl=~\"[[fullurl]]\"} offset 24h > 0)",
     "legendFormat": "昨日-p99"
    },
    {
     "expr": "avg(job:nginx_http_request_duration_seconds:p99_by_host_instance_fullurl_2XX{host=~\"[[host]]\", fullurl=~\"[[fullurl]]\"} offset 7d > 0)",
     "legendFormat": "上周-p99"
    }
   ]
  },
  {
   "title": "P999 - 同比环比",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(job:nginx_http_request_duration_seconds:p99_by_host_instance_fullurl_2XX{host=~\"[[host]]\", fullurl=~\"[[fullurl]]\"} > 0)",
     "legendFormat": "当日-p999"
    },
    {
     "expr": "avg(job:nginx_http_request_duration_seconds:p99_by_host_instance_fullurl_2XX{host=~\"[[host]]\", fullurl=~\"[[fullurl]]\"} offset 24h > 0)",
     "legendFormat": "昨日-p999"
    },
    {
     "expr": "avg(job:nginx_http_request_duration_seconds:p99_by_host_instance_fullurl_2XX{host=~\"[[host]]\", fullurl=~\"[[fullurl]]\"} offset 7d > 0)",
     "legendFormat": "上周-p999"
    }
   ]
  }
 ]
}