{
 "title": "API / Dashboard",
 "tags": [ "nginx" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": "label_values(nginx_http_request_duration_seconds_count, host)"
   }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ERROR 3XX - 1min",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_http_request_duration_seconds_count{host=~\"$host\", status=~\"3..\"}[1m])) by (host)",
     "legendFormat": "3XX - 1min - {{host}}"
    }
   ]
  },
  {
   "title": "2XX QPS By Host",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (job:nginx_http_request_duration_seconds:qps_by_instance_host_endpoint_2XX{host=~\"$host\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(job:nginx_http_request_duration_seconds:qps_by_instance_host_endpoint_2XX{host=~\"$host\"})",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(job:nginx_http_request_duration_seconds:qps_by_instance_host_status_method_4XX{host=~\"$host\"})",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(job:nginx_http_request_duration_seconds:qps_by_instance_host_status_method_5XX{host=~\"$host\"})",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "ERROR 4XX - 1min",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_http_request_duration_seconds_count{host=~\"$host\", status=~\"40[^3]{1}|4[^0]{1}.\"}[1m])) by (host)",
     "legendFormat": "4XX - 1min - {{host}}"
    }
   ]
  },
  {
   "title": "4XX QPS By Host",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(job:nginx_http_request_duration_seconds:qps_by_instance_host_status_method_4XX{host=~\"$host\"}) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "ERROR Rate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "job:nginx_http_request_duration_seconds_sum:err_rate_by_host{host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "ERROR 5XX - 1min",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_http_request_duration_seconds_count{host=~\"$host\", status=~\"5..\"}[1m])) by (host)",
     "legendFormat": "5XX - 1min - {{host}}"
    }
   ]
  },
  {
   "title": "5XX QPS By Host",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(job:nginx_http_request_duration_seconds:qps_by_instance_host_status_method_5XX{host=~\"$host\"}) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Endpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(job:nginx_http_request_duration_seconds:qps_by_instance_host_status_method_2XX{host=~\"$host\"}) by (host)"
    },
    {
     "expr": "sum(increase(nginx_http_request_duration_seconds_count{host=~\"$host\", status=~\"3..\"}[1m])) by (host)"
    },
    {
     "expr": "sum(job:nginx_http_request_duration_seconds:qps_by_instance_host_status_method_4XX{host=~\"$host\"}) by (host)"
    },
    {
     "expr": "sum(job:nginx_http_request_duration_seconds:qps_by_instance_host_status_method_5XX{host=~\"$host\"}) by (host)"
    },
    {
     "expr": "100-job:nginx_http_request_duration_seconds_sum:err_rate_by_host{host=~\"$host\"}"
    }
   ]
  }
 ]
}