{
 "title": "OpenResty Lua Prometheus Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": "label_values(nginx_http_request_duration_seconds_count, host)"
   },
   {
    "name": "endpoint",
    "label": "endpoint",
    "query": "label_values(nginx_http_request_duration_seconds_count{host=~\"$host\"}, endpoint)"
   },
   {
    "name": "fullurl",
    "label": "fullurl",
    "query": "label_values(nginx_http_request_duration_seconds_count{host=~\"$host\",endpoint=~\"$endpoint\"}, fullurl)"
   }
  ]
 },
 "panels": [
  {
   "title": "QPS By Host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_request_duration_seconds_count{}[3m])) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "QPS By Endpoint",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_request_duration_seconds_count{host=~\"$host\"}[3m])) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Latency P99 By Host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n  sum by(host, le) (rate(nginx_http_request_duration_seconds_bucket{host=~\"$host\"}[3m])))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "$fullurl", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }, "repeat": "fullurl" },
  {
   "title": "QPS - $fullurl",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_request_duration_seconds_count{host=~\"$host\"}[3m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Latency P99",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90,\n  sum by(le) (rate(nginx_http_request_duration_seconds_bucket{fullurl=~\"$fullurl\"}[3m])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99,\n  sum by(le) (rate(nginx_http_request_duration_seconds_bucket{fullurl=~\"$fullurl\"}[3m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.999,\n  sum by(le) (rate(nginx_http_request_duration_seconds_bucket{fullurl=~\"$fullurl\"}[3m])))",
     "legendFormat": "P999"
    }
   ]
  },
  {
   "title": "Latency P99",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n  sum by(instance, le) (rate(nginx_http_request_duration_seconds_bucket{fullurl=~\"$fullurl\"}[3m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Latency P999",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999,\n  sum by(instance, le) (rate(nginx_http_request_duration_seconds_bucket{fullurl=~\"$fullurl\"}[3m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "错误数（5 min）",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 17, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_http_request_duration_seconds_count{endpoint=~\"[[endpoint]]\", fullurl=~\"[[fullurl]]\", status=~\"3..\"}[5m]))",
     "legendFormat": "3XX"
    },
    {
     "expr": "sum(increase(nginx_http_request_duration_seconds_count{endpoint=~\"[[endpoint]]\", fullurl=~\"[[fullurl]]\", status=~\"40[^3]{1}|4[^0]{1}.\"}[5m]))",
     "legendFormat": "4XX(with out 401 & 403)"
    },
    {
     "expr": "sum(increase(nginx_http_request_duration_seconds_count{endpoint=~\"[[endpoint]]\", fullurl=~\"[[fullurl]]\", status=~\"5..\"}[5m]))",
     "legendFormat": "5XX"
    },
    {
     "expr": "sum(increase(nginx_http_request_duration_seconds_count{endpoint=~\"[[endpoint]]\", fullurl=~\"[[fullurl]]\", status=~\"2..\"}[5m]))",
     "legendFormat": "3XX"
    }
   ]
  }
 ]
}