{
 "title": "NGINX / API / Host / Endpoint / URL",
 "tags": [ "nginx" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": "label_values(job:nginx_http_request_duration_seconds:qps_by_instance_host_endpoint_2XX, host)"
   },
   {
    "name": "endpoint",
    "label": "endpoint",
    "query": "label_values(job:nginx_http_request_duration_seconds:qps_by_instance_host_endpoint_2XX{host=~\"$host\"}, endpoint)"
   },
   {
    "name": "fullurl",
    "label": "fullurl",
    "query": "label_values(job:nginx_http_request_duration_seconds:qps_by_instance_host_endpoint_fullurl_2XX{host=~\"$host\",endpoint=~\"$endpoint\"}, fullurl)"
   }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ERROR Rate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "job:nginx_http_request_duration_seconds_sum:err_rate_by_host_endpoint_fullurl{host=~\"$host\", endpoint=~\"$endpoint\"}",
     "legendFormat": "{{fullurl}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:nginx_http_request_duration_seconds:qps_by_host_endpoint_2XX{host=~\"$host\", endpoint=~\"$endpoint\"}",
     "legendFormat": "2XX"
    },
    {
     "expr": "job:nginx_http_request_duration_seconds:qps_by_host_endpoint_3XX{host=~\"$host\", endpoint=~\"$endpoint\"}",
     "legendFormat": "3XX"
    },
    {
     "expr": "job:nginx_http_request_duration_seconds:qps_by_host_endpoint_4XX{host=~\"$host\", endpoint=~\"$endpoint\"}",
     "legendFormat": "4XX"
    },
    {
     "expr": "job:nginx_http_request_duration_seconds:qps_by_host_endpoint_5XX{host=~\"$host\", endpoint=~\"$endpoint\"}",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:nginx_http_request_duration_seconds:qps_by_host_endpoint_fullurl_2XX{host=~\"$host\", endpoint=~\"$endpoint\"}",
     "legendFormat": "{{fullurl}}"
    }
   ]
  },
  { "title": "$fullurl", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "fullurl" },
  {
   "title": "ERR Count - 1min",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:nginx_http_request_duration_seconds_count:counter_1min_by_host_3XX_endpoint_fullurl_instance{host=~\"$host\", endpoint=~\"$endpoint\", fullurl=~\"$fullurl\"}",
     "legendFormat": "3XX - {{instance}}"
    },
    {
     "expr": "job:nginx_http_request_duration_seconds_count:counter_1min_by_host_5XX_endpoint_fullurl_instance{host=~\"$host\", endpoint=~\"$endpoint\", fullurl=~\"$fullurl\"}",
     "legendFormat": "5XX - {{instance}}"
    },
    {
     "expr": "job:nginx_http_request_duration_seconds_count:counter_1min_by_host_4XX_endpoint_fullurl_instance{host=~\"$host\", endpoint=~\"$endpoint\", fullurl=~\"$fullurl\"}",
     "legendFormat": "4XX(with out 401 & 403) - {{instance}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "job:nginx_http_request_duration_seconds:p999_by_host_fullurl_2XX{host=~\"$host\", fullurl=~\"$fullurl\"}",
     "legendFormat": "p999"
    },
    {
     "expr": "job:nginx_http_request_duration_seconds:p99_by_host_fullurl_2XX{host=~\"$host\", fullurl=~\"$fullurl\"}",
     "legendFormat": "p99"
    },
    {
     "expr": "job:nginx_http_request_duration_seconds:p90_by_host_fullurl_2XX{host=~\"$host\", fullurl=~\"$fullurl\"}",
     "legendFormat": "p90"
    },
    {
     "expr": "job:nginx_http_request_duration_seconds:avg_by_host_fullurl_2XX{host=~\"$host\", fullurl=~\"$fullurl\"}",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "2XX QPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:nginx_http_request_duration_seconds:qps_by_host_endpoint_fullurl_2XX{host=~\"$host\", endpoint=~\"$endpoint\", fullurl=~\"$fullurl\"}",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "2XX P90",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "job:nginx_http_request_duration_seconds:p90_by_host_instance_fullurl_2XX{host=~\"$host\", fullurl=~\"$fullurl\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "2XX P99",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "job:nginx_http_request_duration_seconds:p99_by_host_instance_fullurl_2XX{host=~\"$host\", fullurl=~\"$fullurl\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "2XX P999",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "job:nginx_http_request_duration_seconds:p999_by_host_instance_fullurl_2XX{host=~\"$host\", fullurl=~\"$fullurl\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "2XX QPS By Instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:nginx_http_request_duration_seconds:qps_by_instance_host_endpoint_fullurl_2XX{host=~\"$host\", endpoint=~\"$endpoint\", fullurl=~\"$fullurl\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "P90 - History Diff",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "job:nginx_http_request_duration_seconds:p90_by_host_fullurl_2XX{host=~\"$host\", fullurl=~\"$fullurl\"}",
     "legendFormat": "ToDay - p90"
    },
    {
     "expr": "job:nginx_http_request_duration_seconds:p90_by_host_fullurl_2XX{host=~\"$host\", fullurl=~\"$fullurl\"} offset 24h",
     "legendFormat": "LastDay - p90"
    },
    {
     "expr": "job:nginx_http_request_duration_seconds:p90_by_host_fullurl_2XX{host=~\"$host\", fullurl=~\"$fullurl\"} offset 7d",
     "legendFormat": "LastWeek - p90"
    }
   ]
  },
  {
   "title": "P99 - History Diff",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "job:nginx_http_request_duration_seconds:p99_by_host_fullurl_2XX{host=~\"$host\", fullurl=~\"$fullurl\"}",
     "legendFormat": "Today - p99"
    },
    {
     "expr": "job:nginx_http_request_duration_seconds:p99_by_host_fullurl_2XX{host=~\"$host\", fullurl=~\"$fullurl\"} offset 24h",
     "legendFormat": "LastDay - p99"
    },
    {
     "expr": "job:nginx_http_request_duration_seconds:p99_by_host_fullurl_2XX{host=~\"$host\", fullurl=~\"$fullurl\"} offset 7d",
     "legendFormat": "LastWeek - p99"
    }
   ]
  },
  {
   "title": "P999 - History Diff",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "job:nginx_http_request_duration_seconds:p999_by_host_fullurl_2XX{host=~\"$host\", fullurl=~\"$fullurl\"}",
     "legendFormat": "Today - p999"
    },
    {
     "expr": "job:nginx_http_request_duration_seconds:p999_by_host_fullurl_2XX{host=~\"$host\", fullurl=~\"$fullurl\"} offset 24h",
     "legendFormat": "LastDay - p999"
    },
    {
     "expr": "job:nginx_http_request_duration_seconds:p999_by_host_fullurl_2XX{host=~\"$host\", fullurl=~\"$fullurl\"} offset 7d",
     "legendFormat": "LastWeek - p999"
    }
   ]
  }
 ]
}